kind: Deployment
apiVersion: apps/v1
metadata:
   name: vamshi
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: vamshi
   template:
      metadata:
        labels:
          app: vamshi
      spec:
       containers:
        - name: vamshi
          image: kesarivamshi/kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 80
