kind: Service                             
apiVersion: v1
metadata:
  name: vamshi
  labels:
    app: vamshi
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: vamshi                    
  type: LoadBalancer                   
